### ISSUE TITLE
Tester KeeWeb HTTP

### ISSUE THREAD

**Issue by ColinMaudry** [ColinMaudry/password-management#25]
KeeWeb HTTP est un plugin permettant de remplir automatiquement les mots de passe dans le navigateur.

Il souffre d'une faille de sécurité, mais celle-ci est très limitée lors d'une utilisation locale : https://github.com/pfn/keepasshttp/issues/258

La faible gravité me fait penser que cette approche est compatible avec le modèle de menace (#10).

Cet issue est pour @H--o-l :tada:

**Comment by H--o-l** [comment]
J'utilse le pluging KeeWebHttp et les extensions KeePassHttp-Connector Chrome & KeePassHttp-Connector Firefox  depuis quelque jours, sur Linux (Fedora) et Windows 10.

J'en suis heureux, la détection des champs de login est, je trouve, moin enviassante qu'avec LastPass.
Elle ne pop-up pas quand :
- elle a un doute
- KeeWeb n'est pas connecté
- KeeWeb est connecté, mais sans coffre ouvert

Si elle n'est pas apparu, il est possible de l'appeler via un click droit ou deux raccourcis clavier :

![Screenshot from 2019-12-13 10-32-09](https://user-images.githubusercontent.com/10905922/70790061-8f042400-1d94-11ea-8e21-61aabd9de06e.png)

La génération d'un nouveau mot de passe ressemble à cela :

![toto](https://user-images.githubusercontent.com/10905922/70790103-a3482100-1d94-11ea-8827-ee7dc9d161dc.png)

Et lorsque plusieurs mot de passe sont enregistrés pour un site :

![Screenshot from 2019-12-13 10-39-16](https://user-images.githubusercontent.com/10905922/70790451-616baa80-1d95-11ea-9c05-ee211e42041b.png)

C'est parfait pour moi !

**Comment by ColinMaudry** [comment]
Mercccciiiiiii !
